name: flutter_app
description: Flutter mobile app for AndroidInsta project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  timeago: ^3.6.1
  web_socket_channel: ^2.4.5
  stomp_dart_client: ^2.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.0
  package_info_plus: 7.0.0
  # Video player dependencies for Reels
  video_player: ^2.9.0
  chewie: ^1.8.5
  file_picker: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
